function goBack() {
    // Überprüfen, ob die vorherige Seite auf moritzgauss.com liegt
    if (document.referrer.includes('moritzgauss.com')) {
      window.history.back();
    } else {
      // Zur Startseite weiterleiten
      window.location.href = '/';
    }
  }
  
  const translations = {
    "en": `
     <p>
    Disclaimer <br> <br>
    Copyright <br>
    The text, images, graphics, sound files, animation files, video files, and their arrangement on the Moritz Gauss website are all subject to copyright and other intellectual property protection. The content of this website may not be copied, distributed,
     modified or made accessible to third parties for commercial purposes. No part of the site may be reproduced in any form or processed, copied or otherwise distributed using electronic systems without written authorisation. We would like to point
     out that some of the images contained on the website are subject to the copyright of third parties.<br><br>
    Liability <br>
    This website has been compiled with the greatest possible care. Nevertheless, no guarantee can be given for the correctness and accuracy of the information it contains. Any liability for damages arising directly or indirectly from the use of this
     website is excluded, unless they are based on intent or gross negligence. Moritz Gauss accepts no responsibility for the content of websites operated by third parties to which reference is made on this website. <br><br>
    Trademarks <br>
    The trademarks on this website are protected by trademark law. This applies in particular to brands, logos and emblems. <br><br>
    Google Analytics <br>
    We use Google Analytics, a web analytics service provided by Google Inc (“Google”). Google uses cookies. The information generated by the cookie about the use of the online offer by the user is usually transmitted to a Google server in the USA
    and stored there.
     Google will use this information on our behalf to analyse the use of our online offer by users, to compile reports on the activities within this online offer and to provide us with further services associated with the use of this online offer and the use of
     the Internet. Pseudonymised user profiles can be created from the processed data.
    We only use Google Analytics with activated IP anonymisation. This means that the IP address of users is truncated by Google within member states of the European Union or in other signatory states to the Agreement on the European Economic
     Area. Only in exceptional cases will the full IP address be transmitted to a Google server in the USA and truncated there. The IP address transmitted by the user’s browser will not be merged with other Google data.
    Users can prevent the storage of cookies by setting their browser software accordingly; users can also prevent Google from collecting the data generated by the cookie and relating to their use of the online offer and from processing this data by
     Google by downloading and installing the browser plug-in available under the following link: http://tools.google.com/dlpage/gaoptout?hl=de or by clicking on the following link: [link wp-ga-opt-out]
    You can find further information on the use of data for advertising purposes by Google, setting and objection options on the Google websites: https://www.google.com/intl/de/policies/privacy/partners/ (“Data use by Google when you use our
     partners’ websites or apps”), http://www.google.com/policies/technologies/ads (“Data use for advertising purposes”), http://www.google.de/settings/ads (“Manage information that Google uses to show you advertising”) and
     http://www.google.com/ads/preferences/ (“Determine which advertising Google shows you”). <br><br>
    Terms & Conditions <br><br>
    1. Application <br>
    1.1. The following Terms and Conditions of Business apply to all design contracts and quotations of the Designer Moritz Gauss. These General Terms and Conditions of Business become an integral part of the Design Contract that comes into being
     between the parties no later than at the time of acceptance of the offer/quotation or individual parts thereof. <br><br>
    2. Cooperation of the Client <br>
    2.1. The Client ensures that all information about the product to be designed, in particular on manufacturing, distribution and retailing, is made available to Moritz Gauss directly and without delay throughout the entire development phase. <br><br>
    3. Confidentiality <br>
    3.1. Moritz Gauss undertakes to maintain confidentiality about all information and documents that become accessible to it in connection with the Design Contract and not to pass on the same to third parties. Moritz Gauss will also oblige its
     employees and agents to protect the business and trade secrets of the Client. <br>
    
    3.2.. The same obligations apply to the Client with regard to the business and trade secrets of Moritz Gauss. This also applies in particular to the ideas and study models brought to the Client’s attention during the development phase. <br><br>
    4. Acceptance <br>
    4.1. Moritz Gauss mutually agrees with the Client on dates for the presentation of the individual project phases in text form or delivers the product of the project phase to the Client. <br>
    
    4.2. Each of the project phases must be separately accepted. Acceptance is deemed to have taken place at the latest if the Client has made no objections in text form within ten working days of presentation of the project phase or delivery of the
     product. Thereafter, Moritz Gauss issues the invoice and the Client pays the remuneration due. <br><br>
    5. Liability <br>
    5.4. The liability of Moritz Gauss for damages to the Client is limited in terms of the amount to the remuneration paid to Moritz Gauss. <br>
     5.5. Moritz Gauss does not store the data in its archives after the project has ended and been paid for. <br><br>
    6. Property Rights <br>
    6.1. The design models, technical drawings, prototypes and files of Moritz Gauss are protected rights. <br>
    
    6.2. The design products of Moritz Gauss may only be used for the agreed type of use, for the agreed purpose and to the agreed extent. The Client acquires the right of use only after payment in full of the agreed remuneration for all phases of the
     project. <br>
    
    6.3. Imitation of the design or elements thereof is admissible only with the prior consent of Moritz Gauss. Any further transfer or licensing to third parties, respectively OEM (Original Equipment Manufacturer), of the rights of use and all existing
     property rights for the same also requires the prior written consent of Moritz Gauss. <br>
    
    6.4. A design created by Moritz Gauss may not be modified, processed, further developed or transferred to other products without prior consent. <br>
    
    6.5. The rights to use drafts and concepts, in particular preliminary drafts, variations, design concepts and studies of the final design product are not transferred to the Client as these rights merely facilitate the development of, and the decision-
     making process for selection of, the final design. <br>
    
    6.6. Moritz Gauss must be named as designer on all design products and representations of the design products. The wording "Designed by Moritz Gauss" must be used. <br><br>
    7. Specimen Copy <br>
    7.1. Moritz Gauss reserves the right to declare the approval of the design product. To this purpose, the Client is obliged to submit the final version of the prototype or other model before the commencement of serial production. <br>
     7.2. After receipt of the confirmation of order, Moritz Gauss may name the Client as reference in its own advertising. <br>
    7.3. Moritz Gauss may publish representations of the design product created using its services as well as advertising materials referring to the same and use them for its own advertising. <br>
</p>
    `,
    "de": `
      

<p>
    Disclaimer <br> <br>
    Urheberrecht <br>
    Die Texte, Bilder, Grafiken, Tondateien, Animationsdateien, Videodateien und deren Anordnung auf der Website von Moritz Gauss unterliegen dem Urheberrecht und anderen Gesetzen zum Schutz geistigen Eigentums. Der Inhalt dieser Website darf nicht zu
    kommerziellen Zwecken kopiert, verbreitet, verändert oder Dritten zugänglich gemacht werden. Kein Teil der Website darf in irgendeiner Form reproduziert, bearbeitet, kopiert oder anderweitig unter Verwendung elektronischer Systeme verbreitet
    werden, ohne schriftliche Genehmigung. Wir weisen darauf hin, dass einige der auf der Website enthaltenen Bilder dem Urheberrecht Dritter unterliegen.<br><br>
    Haftung <br>
    Diese Website wurde mit größtmöglicher Sorgfalt zusammengestellt. Dennoch kann keine Garantie für die Fehlerfreiheit und Genauigkeit der enthaltenen Informationen übernommen werden. Jegliche Haftung für Schäden, die direkt oder indirekt aus der
    Nutzung dieser Website entstehen, ist ausgeschlossen, sofern sie nicht auf Vorsatz oder grober Fahrlässigkeit beruhen. Moritz Gauss übernimmt keine Verantwortung für den Inhalt von Websites Dritter, auf die auf dieser Website verwiesen wird. <br><br>
    Marken <br>
    Die auf dieser Website enthaltenen Marken sind markenrechtlich geschützt. Dies gilt insbesondere für Marken, Logos und Embleme. <br><br>
    Google Analytics <br>
    Wir nutzen Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Google verwendet Cookies. Die durch das Cookie erzeugten Informationen über die Nutzung des Online-Angebots durch die Nutzer werden in der Regel an einen Server
    von Google in den USA übertragen und dort gespeichert.
    Google wird diese Informationen in unserem Auftrag verwenden, um die Nutzung unseres Online-Angebots durch die Nutzer auszuwerten, Berichte über die Aktivitäten innerhalb dieses Online-Angebots zusammenzustellen und uns weitere mit der
    Nutzung dieses Online-Angebots und der Internetnutzung verbundene Dienstleistungen zu erbringen. Aus den verarbeiteten Daten können pseudonymisierte Nutzungsprofile erstellt werden.
    Wir verwenden Google Analytics nur mit aktivierter IP-Anonymisierung. Das bedeutet, dass die IP-Adresse der Nutzer von Google innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den
    Europäischen Wirtschaftsraum gekürzt wird. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Die vom Browser des Nutzers übermittelte IP-Adresse wird nicht mit anderen Daten
    von Google zusammengeführt.
    Nutzer können die Speicherung der Cookies durch eine entsprechende Einstellung ihrer Browser-Software verhindern; Nutzer können auch die Erfassung der durch das Cookie erzeugten und auf ihre Nutzung des Online-Angebots bezogenen Daten
    durch Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plug-in herunterladen und installieren: http://tools.google.com/dlpage/gaoptout?hl=de oder durch Klicken auf
    den folgenden Link: [link wp-ga-opt-out]
    Weitere Informationen zur Datennutzung zu Werbezwecken durch Google, Einstellungs- und Widerspruchsmöglichkeiten finden Sie auf den Webseiten von Google: https://www.google.com/intl/de/policies/privacy/partners/ („Datennutzung durch Google,
    wenn Sie Websites oder Apps unserer Partner nutzen“), http://www.google.com/policies/technologies/ads („Datennutzung für Werbezwecke“), http://www.google.de/settings/ads („Verwalten Sie die Informationen, die Google verwendet, um Ihnen
    Werbung zu zeigen“) und http://www.google.com/ads/preferences/ („Bestimmen Sie, welche Werbung Google Ihnen zeigt“). <br><br>
    Allgemeine Geschäftsbedingungen <br><br>
    1. Geltungsbereich <br>
    1.1. Die nachfolgenden Allgemeinen Geschäftsbedingungen gelten für alle Designverträge und Angebote des Designers Moritz Gauss. Diese Allgemeinen Geschäftsbedingungen werden spätestens mit der Annahme des Angebots oder einzelner Teile davon
    Bestandteil des Designvertrags zwischen den Parteien. <br><br>
    2. Mitwirkung des Auftraggebers <br>
    2.1. Der Auftraggeber stellt sicher, dass sämtliche Informationen zum zu gestaltenden Produkt, insbesondere zu Herstellung, Vertrieb und Vermarktung, Moritz Gauss direkt und unverzüglich während der gesamten Entwicklungsphase zur Verfügung gestellt
    werden. <br><br>
    3. Vertraulichkeit <br>
    3.1. Moritz Gauss verpflichtet sich, über alle ihm im Zusammenhang mit dem Designvertrag zugänglich werdenden Informationen und Unterlagen Stillschweigen zu bewahren und diese nicht an Dritte weiterzugeben. Moritz Gauss verpflichtet auch seine
    Mitarbeiter und Beauftragten, die Geschäfts- und Betriebsgeheimnisse des Auftraggebers zu wahren. <br>
    
    3.2. Die gleichen Verpflichtungen gelten für den Auftraggeber in Bezug auf die Geschäfts- und Betriebsgeheimnisse von Moritz Gauss. Dies gilt insbesondere auch für die dem Auftraggeber während der Entwicklungsphase vorgelegten Ideen und Studien-
    Modelle. <br><br>
    4. Abnahme <br>
    4.1. Moritz Gauss vereinbart mit dem Auftraggeber Termine für die Präsentation der einzelnen Projektphasen in Textform oder liefert das Produkt der jeweiligen Projektphase an den Auftraggeber. <br>
    
    4.2. Jede der Projektphasen ist gesondert abzunehmen. Die Abnahme gilt spätestens als erfolgt, wenn der Auftraggeber nicht innerhalb von zehn Arbeitstagen nach Präsentation der Projektphase oder Lieferung des Produkts schriftlich Einwände erhebt.
    Anschließend stellt Moritz Gauss die Rechnung aus, und der Auftraggeber zahlt die fällige Vergütung. <br><br>
    5. Haftung <br>
    5.4. Die Haftung von Moritz Gauss für Schäden gegenüber dem Auftraggeber ist der Höhe nach auf die an Moritz Gauss gezahlte Vergütung beschränkt. <br>
    5.5. Moritz Gauss speichert die Daten nach Abschluss und Bezahlung des Projekts nicht in seinen Archiven. <br><br>
    6. Urheberrechte <br>
    6.1. Die Entwurfsmodelle, technischen Zeichnungen, Prototypen und Dateien von Moritz Gauss sind geschützte Rechte. <br>
    
    6.2. Die Designprodukte von Moritz Gauss dürfen nur für die vereinbarte Nutzungsart, den vereinbarten Zweck und in dem vereinbarten Umfang verwendet werden. Das Nutzungsrecht erwirbt der Auftraggeber erst nach vollständiger Zahlung der vereinbarten
    Vergütung für alle Projektphasen. <br>
    
    6.3. Die Nachahmung des Designs oder von Elementen desselben ist nur mit vorheriger Zustimmung von Moritz Gauss zulässig. Jede weitere Übertragung oder Lizenzierung der Nutzungsrechte sowie aller bestehenden Schutzrechte an Dritte oder OEM
    (Original Equipment Manufacturer) bedarf ebenfalls der vorherigen schriftlichen Zustimmung von Moritz Gauss. <br>
    
    6.4. Ein von Moritz Gauss entworfenes Design darf ohne vorherige Zustimmung nicht verändert, bearbeitet, weiterentwickelt oder auf andere Produkte übertragen werden. <br>
    
    6.5. Die Nutzungsrechte an Entwürfen und Konzepten, insbesondere Vorentwürfen, Varianten, Designkonzepten und Studien des finalen Designprodukts, werden nicht auf den Auftraggeber übertragen, da diese lediglich der Entwicklung und Entscheidungsfindung
    für die Auswahl des finalen Designs dienen. <br>
    
    6.6. Moritz Gauss muss auf allen Designprodukten und Darstellungen der Designprodukte als Designer genannt werden. Die Formulierung „Designed by Moritz Gauss“ ist zu verwenden. <br><br>
    7. Belegexemplar <br>
    7.1. Moritz Gauss behält sich das Recht vor, die Freigabe des Designprodukts zu erklären. Zu diesem Zweck ist der Auftraggeber verpflichtet, die endgültige Version des Prototyps oder eines anderen Modells vor Beginn der Serienproduktion vorzulegen. <br>
    7.2. Nach Erhalt der Auftragsbestätigung darf Moritz Gauss den Auftraggeber als Referenz in seiner eigenen Werbung benennen. <br>
    7.3. Moritz Gauss darf Darstellungen des von ihm entworfenen Designprodukts sowie Werbematerialien, die darauf Bezug nehmen, veröffentlichen und für eigene Werbezwecke verwenden. <br>
</p>
`
  };
  
  
  function setLanguage(lang) {
    if (translations[lang]) {
      document.getElementById("smalltext").innerHTML = translations[lang];
    } else {
      console.warn(`Language ${lang} is not defined. Defaulting to English.`);
      document.getElementById("smalltext").innerHTML = translations['en'];
    }
  }
  
  // Set default language on page load
  window.onload = () => setLanguage('en');